name: document-generation
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.3.1
  - pip:
    - azure-core==1.26.3
    - azure-identity==1.12.0
    - azure-storage-blob==12.15.0
    - openai==0.26.5